# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "myaccount"
user = "myuser"
password = "mypwd"
role = "EV_ROLE"
warehouse = "EV_WH"
database = "EV_DB"
schema = "ANALYTICS"
